/* Local homepage translations. No service calls, tracking, or storage. */
(() => {
  'use strict';
  const rows = [
["NELDO — Find your next meal", "NELDO — Encuentra tu próxima comida", "NELDO — Encontre sua próxima refeição"],
['Skip to content','Saltar al contenido','Pular para o conteúdo'],
['NELDO home','Inicio de NELDO','Início do NELDO'],
['Main navigation','Navegación principal','Navegação principal'],
['On the menu','Qué cocinamos','No cardápio'],
['How it works','Cómo funciona','Como funciona'],
['Inside the app','Dentro de NELDO','Por dentro do NELDO'],
['About the launch','Sobre el lanzamiento','Sobre o lançamento'],
['Website language','Idioma del sitio','Idioma do site'],
['Switch to light appearance','Cambiar al modo claro','Mudar para o modo claro'],
['Switch to dark appearance','Cambiar al modo oscuro','Mudar para o modo escuro'],
['Light view','Modo claro','Modo claro'],
['Light view ☼','Modo claro ☼','Modo claro ☼'],
['Dark view ☾','Modo oscuro ☾','Modo escuro ☾'],
['Navigation menu','Menú de navegación','Menu de navegação'],
['Menu','Menú','Menu'],
['Mobile navigation','Navegación móvil','Navegação móvel'],
['Launch plans','Planes de lanzamiento','Planos de lançamento'],
['Your data, explained','Tus datos, explicados','Seus dados, explicados'],
['Privacy','Privacidad','Privacidade'],
['Consumer Health Data Privacy Policy','Privacidad de los datos de salud','Privacidade dos dados de saúde'],
['Terms','Términos','Termos'],
["Your next meal, made easier", "Tu próxima comida, más fácil", "Sua próxima refeição, mais fácil"],
['Start with','Empieza por','Comece pelo'],
["what you’re", "lo que te", "que você"],
["craving.", "apetece.", "quer comer."],
['Craving gumbo? Need something quick? Tell NELDO what sounds good, what’s in your kitchen, and how much energy you have. Find a meal that fits—and get help making it.','¿Se te antoja un gumbo? ¿Necesitas algo rápido? Cuéntale a NELDO qué te apetece, qué tienes en la cocina y cuánta energía tienes. Encuentra una comida que encaje contigo y recibe ayuda para prepararla.','Deu vontade de gumbo? Precisa de algo rápido? Conte ao NELDO o que você quer comer, o que tem na cozinha e quanta energia tem. Encontre uma refeição que combine com você e receba ajuda para preparar.'],
['See NELDO in action','Mira cómo funciona NELDO','Veja o NELDO em ação'],
['Explore the meals','Explora las comidas','Explore as refeições'],
['Free core help. No subscription. No required account.','Ayuda básica gratis. Sin suscripción. Sin cuenta obligatoria.','Ajuda básica grátis. Sem assinatura. Sem conta obrigatória.'],
['Less deciding. More getting on with your day.','Menos decisiones. Más tiempo para seguir con tu día.','Menos decisões. Mais tempo para seguir com o seu dia.'],
['Your words. A way forward.','Tus palabras. El siguiente paso.','Suas palavras. Um próximo passo.'],
['Recorded NELDO conversation about chicken and sausage gumbo','Conversación grabada de NELDO sobre gumbo de pollo y salchicha','Conversa gravada do NELDO sobre gumbo de frango e linguiça'],
['Recorded example · Sample recipe','Ejemplo grabado · Receta de muestra','Exemplo gravado · Receita de exemplo'],
['Not just “what could I cook?”','Más que «¿qué podría cocinar?»','Mais que “o que eu poderia cozinhar?”'],
['“What actually fits right now?”','«¿Qué encaja de verdad con este momento?»','“O que realmente combina com este momento?”'],
['What goes into a meal decision','Qué cuenta al elegir una comida','O que conta na escolha de uma refeição'],
['Your time','Tu tiempo','Seu tempo'],
['Your ingredients','Tus ingredientes','Seus ingredientes'],
['Your energy','Tu energía','Sua energia'],
['Your cravings, made practical','Tus antojos, hechos realidad','Sua vontade de comer, na prática'],
['Gumbo kind of day?','¿Hoy se te antoja gumbo?','Hoje é dia de gumbo?'],
['Say that.','Dilo así.','Pode falar.'],
['A favorite dish. A quick bowl. Something worth taking your time over. Start with what sounds good, then make a plan around your kitchen.','Tu plato favorito. Un tazón rápido. Algo que merezca su tiempo. Empieza por lo que te apetece y haz un plan con lo que tienes en tu cocina.','Seu prato favorito. Uma tigela rápida. Algo que merece um pouco mais de tempo. Comece pelo que você quer comer e faça um plano com o que tem na cozinha.'],
['01 / Something with soul','01 / Un plato con alma','01 / Comida com alma'],
['Chicken & sausage gumbo','Gumbo de pollo y salchicha','Gumbo de frango e linguiça'],
['A dark roux, smoky sausage, and chicken. Some meals deserve a little time. Start with the dish you actually want.','Roux oscuro, salchicha ahumada y pollo. Algunas comidas merecen su tiempo. Empieza por el plato que realmente quieres.','Roux escuro, linguiça defumada e frango. Algumas refeições merecem um pouco de tempo. Comece pelo prato que você realmente quer.'],
['View the full Chicken & sausage gumbo app screenshot','Ver la captura completa del gumbo de pollo y salchicha','Ver a captura completa do gumbo de frango e linguiça'],
['Recorded chicken and sausage gumbo conversation in NELDO','Conversación grabada sobre gumbo de pollo y salchicha en NELDO','Conversa gravada sobre gumbo de frango e linguiça no NELDO'],
['02 / Know what you need','02 / Ten claro qué necesitas','02 / Saiba do que precisa'],
['Your recipe, ready','Tu receta, lista','Sua receita, pronta'],
['Ingredients, amounts, and servings in one place. Check what you have before you start cooking.','Ingredientes, cantidades y porciones en un solo lugar. Revisa qué tienes antes de empezar a cocinar.','Ingredientes, quantidades e porções em um só lugar. Confira o que você tem antes de começar a cozinhar.'],
['View the full recipe and ingredients screenshot','Ver la captura completa de la receta y los ingredientes','Ver a captura completa da receita e dos ingredientes'],
['Recorded gumbo recipe and ingredients in NELDO','Receta e ingredientes de gumbo grabados en NELDO','Receita e ingredientes de gumbo gravados no NELDO'],
['03 / Bring it to the table','03 / Llévalo a la mesa','03 / Leve à mesa'],
['Cook it together','Cocina con ayuda','Cozinhe com ajuda'],
['Keep the recipe close. Follow the steps and use a timer when the cooking needs your attention.','Ten la receta a mano. Sigue los pasos y usa un temporizador cuando la comida necesite tu atención.','Mantenha a receita por perto. Siga as etapas e use o temporizador quando a comida precisar da sua atenção.'],
['View the full gumbo cooking steps screenshot','Ver la captura completa de los pasos del gumbo','Ver a captura completa das etapas do gumbo'],
['Recorded gumbo cooking step and timer in NELDO','Paso de cocina y temporizador del gumbo grabados en NELDO','Etapa de preparo e temporizador do gumbo gravados no NELDO'],
['Recorded examples from NELDO, using sample recipes. Tap a screen to take a closer look.','Ejemplos grabados de NELDO con recetas de muestra. Toca una pantalla para verla de cerca.','Exemplos gravados do NELDO com receitas de exemplo. Toque numa tela para ver de perto.'],
['Always check ingredients and allergens.','Revisa siempre los ingredientes y alérgenos.','Confira sempre os ingredientes e alérgenos.'],
['Meet your Energy Modes','Conoce tus modos de energía','Conheça seus modos de energia'],
['Different days.','Días diferentes.','Dias diferentes.'],
['Same NELDO.','El mismo NELDO.','O mesmo NELDO.'],
['Energy isn’t a personality type. It’s what you have to work with right now. Pick a mode—or just start talking.','La energía no define tu personalidad. Es con lo que cuentas en este momento. Elige un modo o simplemente empieza a hablar.','Energia não define sua personalidade. É o que você tem para este momento. Escolha um modo ou simplesmente comece a conversar.'],
['A little in the tank','Con poca energía','Com pouca energia'],
['Lowkey','Con calma','Com calma'],
['“I don’t have much in me.”','«Hoy no tengo mucha energía».','“Hoje não tenho muita energia.”'],
['Keep meals manageable. Less prep, fewer steps, and less to clean up.','Comidas fáciles de llevar. Menos preparación, menos pasos y menos que limpiar.','Refeições que você dá conta de fazer. Menos preparo, menos etapas e menos louça.'],
['Low energy. Still fed.','Poca energía. Igual comes bien.','Pouca energia. Ainda dá para comer.'],
['Your usual pace','Tu ritmo de siempre','Seu ritmo de sempre'],
['Everyday','Cotidiano','Cotidiano'],
['“Just a normal kind of day.”','«Un día como cualquier otro».','“Um dia como outro qualquer.”'],
['A familiar, satisfying meal that fits the time and ingredients you have.','Una comida familiar y sabrosa que encaje con tu tiempo y tus ingredientes.','Uma refeição familiar e gostosa que combine com seu tempo e seus ingredientes.'],
['A good everyday meal.','Una buena comida para cada día.','Uma boa refeição para o dia a dia.'],
['Room for a little more','Con ganas de hacer algo más','Com vontade de caprichar'],
['Locked In','A fondo','Com dedicação'],
['“I’ve got energy. Let’s cook.”','«Tengo energía. Vamos a cocinar».','“Estou com energia. Vamos cozinhar.”'],
['Take your time. Try a technique or a more involved dish—because you want to.','Tómate tu tiempo. Prueba una técnica o un plato más elaborado porque te apetece.','Cozinhe com calma. Experimente uma técnica ou um prato mais elaborado porque você quer.'],
['More ambition. Your call.','Más ganas de cocinar. Tú eliges.','Mais vontade de cozinhar. Você escolhe.'],
['A pace for right now','Un ritmo para este momento','Um ritmo para este momento'],
['Same chat.','La misma conversación.','A mesma conversa.'],
['Your kind of day.','A tu ritmo.','No seu ritmo.'],
['Preview an energy mode','Ver un modo de energía','Ver um modo de energia'],
['A familiar meal at your usual pace. Enough room to cook, without making it a project.','Una comida familiar a tu ritmo de siempre. Espacio para cocinar sin convertirlo en un proyecto.','Uma refeição familiar no seu ritmo de sempre. Espaço para cozinhar sem virar um projeto.'],
['Keep it manageable. Less prep, fewer steps, and something good to eat with the energy you have.','Hazlo fácil. Menos preparación, menos pasos y algo rico con la energía que tienes.','Facilite as coisas. Menos preparo, menos etapas e algo gostoso com a energia que você tem.'],
['A little more room to explore. Try a technique or a more involved dish when you feel like cooking.','Un poco más de espacio para explorar. Prueba una técnica o un plato más elaborado cuando tengas ganas.','Um pouco mais de espaço para explorar. Experimente uma técnica ou um prato mais elaborado quando estiver com vontade.'],
['See how each mode fits a different kind of day.','Mira cómo cada modo encaja con un día diferente.','Veja como cada modo combina com um dia diferente.'],
['Everyday selected on NELDO’s updated chat home','Modo Cotidiano seleccionado en NELDO','Modo Cotidiano selecionado no NELDO'],
['Everyday selected in NELDO','Modo Cotidiano seleccionado en NELDO','Modo Cotidiano selecionado no NELDO'],
['Lowkey selected in NELDO','Modo Con calma seleccionado en NELDO','Modo Com calma selecionado no NELDO'],
['Locked In selected in NELDO','Modo A fondo seleccionado en NELDO','Modo Com dedicação selecionado no NELDO'],
['Recorded app screen','Pantalla grabada de la app','Tela gravada do app'],
['No mode is better than another. Your time, preferences, and constraints still matter.','Ningún modo es mejor que otro. Tu tiempo, tus preferencias y tus límites siguen contando.','Nenhum modo é melhor que outro. Seu tempo, suas preferências e seus limites continuam contando.'],
['Start with a conversation','Empieza con una conversación','Comece com uma conversa'],
['You don’t need','No necesitas','Você não precisa'],
['a better prompt.','la frase perfecta.','da frase perfeita.'],
['Just your words.','Solo tus palabras.','Só das suas palavras.'],
['Tell NELDO what you have, what sounds good, and how much you want to take on. No perfect plan required.','Dile a NELDO qué tienes, qué te apetece y cuánto quieres hacer. No necesitas un plan perfecto.','Conte ao NELDO o que você tem, o que quer comer e quanto quer fazer. Não precisa de um plano perfeito.'],
['Something you could say','Algo que podrías decir','Algo que você pode dizer'],
['“I’m craving gumbo.','«Se me antoja gumbo.','“Estou com vontade de gumbo.'],
['I’ve got time tonight.','Esta noche tengo tiempo.','Hoje tenho tempo.'],
['Let’s make it good.”','Vamos a prepararlo bien».','Vamos caprichar.”'],
['Something you could ask NELDO','Algo que podrías pedirle a NELDO','Algo que você pode pedir ao NELDO'],
['Tell it what you need right now.','Dile qué necesitas ahora.','Conte do que precisa agora.'],
['A dish you’re craving. What’s in the fridge. Twenty minutes before you need to leave. Start wherever you are.','Un plato que se te antoja. Lo que hay en la nevera. Veinte minutos antes de salir. Empieza por donde estés.','Um prato que deu vontade de comer. O que tem na geladeira. Vinte minutos antes de sair. Comece de onde estiver.'],
['Find an option that fits.','Encuentra una opción que encaje.','Encontre uma opção que combine.'],
['NELDO helps narrow the decision around your ingredients, time, and preferred effort. Not another endless recipe scroll.','NELDO te ayuda a elegir según tus ingredientes, tu tiempo y el esfuerzo que quieras dedicar. Sin buscar recetas sin fin.','O NELDO ajuda você a escolher com base nos ingredientes, no tempo e no esforço que quer dedicar. Sem uma busca infinita por receitas.'],
['Make the next step easier.','Facilita el siguiente paso.','Facilite o próximo passo.'],
['Check what you need, follow the cooking steps, or save the recipe for later. The choice stays yours.','Revisa qué necesitas, sigue los pasos o guarda la receta para después. Tú decides.','Confira do que precisa, siga as etapas ou salve a receita para depois. Você decide.'],
['A look inside NELDO','Un vistazo a NELDO','Um olhar por dentro do NELDO'],
['From “what should I eat?”','De «¿qué voy a comer?»','De “o que vou comer?”'],
['to something you can make.','a algo que puedes preparar.','a algo que você pode preparar.'],
['From the first craving to the last cooking step. Take a closer look at your conversation, ingredients, and recipe.','Desde el primer antojo hasta el último paso. Mira de cerca la conversación, los ingredientes y la receta.','Da primeira vontade até a última etapa. Veja de perto a conversa, os ingredientes e a receita.'],
['Choose an app screenshot','Elige una captura de la app','Escolha uma captura do app'],
['Chat','Conversación','Conversa'],
['Your meal','Tu comida','Sua refeição'],
['Recipe','Receta','Receita'],
["Cooking", "Cocinar", "Cozinhar"],
['01 / 04 — Start anywhere','01 / 04 — Empieza por donde quieras','01 / 04 — Comece de onde quiser'],
['A little less deciding. A lot more doing.','Menos decidir. Más hacer.','Menos decidir. Mais fazer.'],
['Breakfast, lunch, dinner, or something in between. Start with a craving, a few ingredients, or whatever energy you have.','Desayuno, almuerzo, cena o algo entre comidas. Empieza con un antojo, algunos ingredientes o la energía que tengas.','Café da manhã, almoço, jantar ou algo entre refeições. Comece com uma vontade, alguns ingredientes ou a energia que tiver.'],
['Three modes, always within reach','Tres modos siempre a mano','Três modos sempre à mão'],
['Your conversation comes first','Tu conversación va primero','Sua conversa vem primeiro'],
['Meals and snacks, all day','Comidas y bocadillos todo el día','Refeições e lanches o dia todo'],
['View full screenshot','Ver la captura completa','Ver a captura completa'],
['NELDO chat home in dark mode with three energy selections','Inicio de NELDO en modo oscuro con tres opciones de energía','Início do NELDO em modo escuro com três opções de energia'],
['NELDO chat home with three visible energy modes','Inicio de NELDO con tres modos de energía visibles','Início do NELDO com três modos de energia visíveis'],
['Recorded example · Dark appearance','Ejemplo grabado · Modo oscuro','Exemplo gravado · Modo escuro'],
['Recorded example · Sample recipe · Dark appearance','Ejemplo grabado · Receta de muestra · Modo oscuro','Exemplo gravado · Receita de exemplo · Modo escuro'],
['Recorded example · Sample recipe · Light appearance','Ejemplo grabado · Receta de muestra · Modo claro','Exemplo gravado · Receita de exemplo · Modo claro'],
['02 / 04 — Your next meal','02 / 04 — Tu próxima comida','02 / 04 — Sua próxima refeição'],
['The useful details. Right in the chat.','Los detalles útiles, en la conversación.','Os detalhes úteis, na conversa.'],
['See the estimated time, effort, servings, and ingredients together. Open the recipe when it sounds right, or save it for another day.','Consulta el tiempo estimado, el esfuerzo, las porciones y los ingredientes. Abre la receta cuando te guste o guárdala para otro día.','Veja o tempo estimado, o esforço, as porções e os ingredientes. Abra a receita quando gostar ou salve para outro dia.'],
['NELDO gumbo conversation and recipe card','Conversación y receta de gumbo en NELDO','Conversa e receita de gumbo no NELDO'],
['Meal facts at a glance','Los datos de la comida de un vistazo','Os detalhes da refeição de uma vez'],
['Cooking method and ingredients','Método de cocción e ingredientes','Modo de preparo e ingredientes'],
['Open or save the recipe','Abre o guarda la receta','Abra ou salve a receita'],
['03 / 04 — Make it happen','03 / 04 — Manos a la obra','03 / 04 — Mãos à obra'],
['From a good idea to something on your plate.','De una buena idea a tu plato.','De uma boa ideia para o seu prato.'],
['Keep the recipe close, check your ingredients, and move into cooking. Your conversation is there when you return.','Ten la receta a mano, revisa tus ingredientes y empieza a cocinar. La conversación seguirá ahí cuando vuelvas.','Mantenha a receita por perto, confira os ingredientes e comece a cozinhar. A conversa continua lá quando você voltar.'],
['NELDO recipe detail with ingredients and cooking actions','Detalle de una receta de NELDO con ingredientes y opciones para cocinar','Detalhes de uma receita do NELDO com ingredientes e opções para cozinhar'],
['Ingredients with amounts','Ingredientes con cantidades','Ingredientes com quantidades'],
['Your recipe in one place','Tu receta en un solo lugar','Sua receita em um só lugar'],
['Back to the same conversation','Vuelve a la misma conversación','Volte à mesma conversa'],
["04 / 04 — Time to cook", "04 / 04 — A cocinar", "04 / 04 — Hora de cozinhar"],
["One step at a time. Your pace.", "Paso a paso. A tu ritmo.", "Uma etapa de cada vez. No seu ritmo."],
["Keep the current step in view, start a timer when you need one, and pick up where you left off.", "Ten a la vista el paso actual, inicia un temporizador cuando lo necesites y retoma donde lo dejaste.", "Mantenha a etapa atual à vista, inicie um temporizador quando precisar e retome de onde parou."],
["Recorded gumbo cooking step and timer in NELDO", "Paso de cocina y temporizador del gumbo grabados en NELDO", "Etapa de preparo e temporizador do gumbo gravados no NELDO"],
["Clear cooking steps", "Pasos de cocina claros", "Etapas de preparo claras"],
["Timers when you need them", "Temporizadores cuando los necesitas", "Temporizadores quando precisar"],
["Resume your cooking", "Retoma la cocina", "Retome o preparo"],
['These recorded examples use sample recipes.','Estos ejemplos grabados usan recetas de muestra.','Estes exemplos gravados usam receitas de exemplo.'],
['Check ingredients and allergens before cooking.','Revisa los ingredientes y alérgenos antes de cocinar.','Confira ingredientes e alérgenos antes de cozinhar.'],
['Useful beyond the suggestion','Ayuda más allá de la sugerencia','Ajuda além da sugestão'],
['A little less work.','Un poco menos de trabajo.','Um pouco menos de trabalho.'],
['All the way through.','De principio a fin.','Do começo ao fim.'],
['01 / In your kitchen','01 / En tu cocina','01 / Na sua cozinha'],
['Start with what','Empieza con lo que','Comece com o que'],
['you already have.','ya tienes.','você já tem.'],
['Tell NELDO your ingredients. Keep what you have and what you need on a grocery list connected to your meal.','Dile a NELDO tus ingredientes. Organiza lo que tienes y lo que necesitas en una lista de compras vinculada a tu comida.','Conte ao NELDO seus ingredientes. Organize o que tem e o que precisa numa lista de compras ligada à sua refeição.'],
['02 / For another day','02 / Para otro día','02 / Para outro dia'],
['Keep the recipe.','Guarda la receta.','Guarde a receita.'],
['Skip the repeat search.','Evita buscarla otra vez.','Evite procurar de novo.'],
['Save a meal, pick up ingredients, and reopen the same recipe when you’re ready to cook.','Guarda una comida, compra los ingredientes y abre la misma receta cuando quieras cocinar.','Salve uma refeição, compre os ingredientes e reabra a mesma receita quando quiser cozinhar.'],
['03 / Food that means something','03 / Comida con significado','03 / Comida com significado'],
['Your cravings.','Tus antojos.','Suas vontades.'],
['Your food traditions.','Tus tradiciones.','Suas tradições.'],
['Name a dish or cuisine, from a Puerto Rican breakfast to gumbo or ramen. Be specific about what you want.','Nombra un plato o una cocina, desde un desayuno puertorriqueño hasta gumbo o ramen. Di exactamente qué te apetece.','Diga um prato ou uma culinária, de um café da manhã porto-riquenho a gumbo ou ramen. Conte exatamente o que quer.'],
['Saved meals stay on the device where you save them. Clearing app or browser storage removes them.','Las comidas guardadas se quedan en el dispositivo donde las guardas. Al borrar el almacenamiento de la app o del navegador, se eliminan.','As refeições salvas ficam no dispositivo onde você as salvou. Apagar o armazenamento do app ou do navegador remove essas refeições.'],
['Allergies & dietary needs','Alergias y necesidades alimentarias','Alergias e necessidades alimentares'],
['Helpful suggestions.','Sugerencias útiles.','Sugestões úteis.'],
['Always double-check.','Revisa siempre.','Confira sempre.'],
['NELDO can make mistakes and cannot guarantee that a meal meets your allergies or dietary needs.','NELDO puede cometer errores y no puede garantizar que una comida se ajuste a tus alergias o necesidades alimentarias.','O NELDO pode cometer erros e não pode garantir que uma refeição atenda às suas alergias ou necessidades alimentares.'],
['Check every ingredient, product label, substitution, and possible allergen cross-contact before preparing or eating food. NELDO cannot verify how food is made or handled, and a recipe or dietary label does not certify that food is safe for you.','Revisa cada ingrediente, etiqueta, sustitución y posible contacto cruzado con alérgenos antes de preparar o comer. NELDO no puede verificar cómo se elabora o manipula la comida; una receta o etiqueta dietética no certifica que sea segura para ti.','Confira cada ingrediente, rótulo, substituição e possível contato cruzado com alérgenos antes de preparar ou comer. O NELDO não pode verificar como a comida é feita ou manipulada; uma receita ou indicação alimentar não certifica que ela seja segura para você.'],
['Add your allergies and ingredients to avoid in the app, and keep them up to date. These guide recipe suggestions; they do not replace your own checks. Review saved recipes again when your needs or ingredients change.','Añade tus alergias e ingredientes que debes evitar en la app y mantenlos al día. Orientan las sugerencias, pero no reemplazan tus propias comprobaciones. Revisa de nuevo las recetas guardadas cuando cambien tus necesidades o ingredientes.','Adicione suas alergias e ingredientes a evitar no app e mantenha tudo atualizado. Isso orienta as sugestões, mas não substitui suas próprias verificações. Reveja as receitas salvas quando suas necessidades ou ingredientes mudarem.'],
['Dietary preferences are not medical advice. Follow your clinician’s guidance for food allergies and medically required diets. If you are unsure whether a food is safe for you, do not eat it until you have verified it.','Las preferencias alimentarias no son consejo médico. Sigue las indicaciones de tu profesional de salud para alergias y dietas médicas. Si no sabes si un alimento es seguro para ti, no lo comas hasta verificarlo.','Preferências alimentares não são orientação médica. Siga as recomendações do seu profissional de saúde para alergias e dietas necessárias. Se não tiver certeza de que um alimento é seguro para você, não coma até verificar.'],
['Read FDA food-allergy guidance','Lee la guía de la FDA sobre alergias alimentarias','Leia a orientação da FDA sobre alergias alimentares'],
['A few things worth knowing','Algunas cosas que conviene saber','Algumas coisas que vale saber'],
['Practical help.','Ayuda práctica.','Ajuda prática.'],
['Clear expectations.','Expectativas claras.','Expectativas claras.'],
["A meal you want to eat. A plan that fits your kitchen. Help with the cooking, one step at a time.", "Una comida que te apetezca. Un plan que encaje con tu cocina. Ayuda para prepararla, paso a paso.", "Uma refeição que você queira comer. Um plano que combine com sua cozinha. Ajuda para preparar, uma etapa de cada vez."],
['Will I need an account or a subscription?','¿Necesitaré una cuenta o suscripción?','Vou precisar de conta ou assinatura?'],
['Core meal help is free, with no required account, subscription, or purchase. You can start without giving your name, email, or phone number.','La ayuda básica con las comidas es gratis, sin cuenta, suscripción ni compra obligatoria. Puedes empezar sin dar tu nombre, correo ni teléfono.','A ajuda básica com refeições é grátis, sem conta, assinatura ou compra obrigatória. Você pode começar sem informar nome, e-mail ou telefone.'],
['Can I use NELDO in my language?','¿Puedo usar NELDO en mi idioma?','Posso usar o NELDO no meu idioma?'],
['NELDO supports English, Spanish, and Portuguese. Choose your language in the app’s settings. You can also change this website’s language above.','NELDO admite inglés, español y portugués. Elige tu idioma en los ajustes de la app. También puedes cambiar el idioma de este sitio arriba.','O NELDO oferece inglês, espanhol e português. Escolha seu idioma nas configurações do app. Você também pode mudar o idioma deste site acima.'],
['Can NELDO order groceries for me?','¿NELDO puede hacer mis compras?','O NELDO pode fazer minhas compras?'],
["Grocery lists help you plan what to buy for your meals. Checkout and delivery are not available here.", "Las listas de compras te ayudan a planificar qué comprar para tus comidas. Aquí no hay pagos ni entregas.", "As listas de compras ajudam a planejar o que comprar para suas refeições. Pagamentos e entregas não estão disponíveis aqui."],
['Do I have to choose an Energy Mode?','¿Tengo que elegir un modo de energía?','Preciso escolher um modo de energia?'],
['No. You can pick Lowkey, Everyday, or Locked In, or just describe what you need. A mode is a starting point—not a label for who you are.','No. Puedes elegir Con calma, Cotidiano o A fondo, o simplemente describir qué necesitas. Un modo es un punto de partida, no una etiqueta sobre quién eres.','Não. Você pode escolher Com calma, Cotidiano ou Com dedicação, ou simplesmente descrever do que precisa. Um modo é um ponto de partida, não um rótulo sobre quem você é.'],
["What can NELDO help me with?", "¿Con qué puede ayudarme NELDO?", "Com o que o NELDO pode me ajudar?"],
["Deciding what to eat, finding a recipe that fits, planning groceries, and cooking with step-by-step help. Save meals you like so your next dinner is easier.", "Decidir qué comer, encontrar una receta que encaje contigo, planificar las compras y cocinar con ayuda paso a paso. Guarda las comidas que te gusten para facilitar la próxima cena.", "Decidir o que comer, encontrar uma receita que combine com você, planejar as compras e cozinhar com ajuda passo a passo. Salve as refeições que gostar para facilitar o próximo jantar."],
["Can NELDO give medical or dietary advice?", "¿NELDO puede dar consejos médicos o dietéticos?", "O NELDO pode dar orientação médica ou alimentar?"],
["NELDO helps with meal ideas and cooking based on the preferences you share. It does not replace a dietitian or clinician. Follow professional guidance for food allergies and medically required diets.", "NELDO ayuda con ideas de comidas y cocina según las preferencias que compartas. No reemplaza a un dietista ni a un profesional médico. Sigue las indicaciones profesionales para alergias y dietas médicas.", "O NELDO ajuda com ideias de refeições e preparo com base nas preferências que você compartilha. Não substitui nutricionista ou profissional de saúde. Siga orientação profissional para alergias e dietas necessárias."],
['NELDO is not a therapist, clinician, or crisis service. If you need urgent support in the U.S. or its territories,','NELDO no es terapeuta, profesional médico ni servicio de crisis. Si necesitas apoyo urgente en EE. UU. o sus territorios,','O NELDO não é terapeuta, profissional de saúde nem serviço de crise. Se precisar de apoio urgente nos EUA ou seus territórios,'],
['call 988','llama al 988','ligue para 988'],
['or','o','ou'],
['text 988','envía un mensaje al 988','envie uma mensagem para 988'],
['. For immediate danger, call 911. Elsewhere, contact your local emergency or crisis service.','. Si hay peligro inmediato, llama al 911. En otros lugares, contacta con el servicio local de emergencias o crisis.','. Em caso de perigo imediato, ligue para 911. Em outros lugares, contate o serviço local de emergência ou crise.'],
['More about 988','Más sobre el 988','Mais sobre o 988'],
['Help shape what’s next','Ayuda a dar forma al futuro','Ajude a construir o que vem a seguir'],
['Your next meal','Tu próxima comida','Sua próxima refeição'],
['doesn’t need to be','no tiene por qué ser','não precisa ser'],
['a whole thing.','tan complicada.','tão complicada.'],
['Good food, at your pace. NELDO is preparing for an adult U.S. beta. For now, explore how it works and get in touch about what’s next.','Buena comida, a tu ritmo. NELDO prepara una beta para adultos en EE. UU. Por ahora, descubre cómo funciona y contacta para saber qué viene después.','Comida boa, no seu ritmo. O NELDO prepara uma versão beta para adultos nos EUA. Por enquanto, explore como funciona e entre em contato para saber o que vem a seguir.'],
['Ask about launch plans','Pregunta por el lanzamiento','Pergunte sobre o lançamento'],
['Public access is not open yet. No signup or purchase is required to explore this website.','El acceso público aún no está abierto. No hace falta registrarse ni comprar para explorar este sitio.','O acesso público ainda não está aberto. Não precisa de cadastro nem compra para explorar este site.'],
['Screenshot preview','Vista de la captura','Prévia da captura'],
['Close screenshot','Cerrar captura','Fechar captura'],
['Close','Cerrar','Fechar'],
['Meet the day you’re having.','Para el día que estás teniendo.','Para o dia que você está vivendo.'],
['Footer navigation','Navegación del pie de página','Navegação do rodapé'],
['Contact','Contacto','Contato'],
['Food safety','Seguridad alimentaria','Segurança alimentar'],
['Safety','Seguridad','Segurança'],
['Good food. Your pace. Your day.','Buena comida. Tu ritmo. Tu día.','Comida boa. Seu ritmo. Seu dia.'],
['Back to top','Volver arriba','Voltar ao topo'],
["Decide what to eat, plan groceries, and cook with help from NELDO. Meals that fit your time, ingredients, and energy.", "Decide qué comer, planifica tus compras y cocina con ayuda de NELDO. Comidas que encajan con tu tiempo, tus ingredientes y tu energía.", "Decida o que comer, planeje suas compras e cozinhe com ajuda do NELDO. Refeições que combinam com seu tempo, seus ingredientes e sua energia."],
["Find a meal that fits your time, ingredients, and energy. Plan your groceries and cook with help from NELDO.", "Encuentra una comida que encaje con tu tiempo, tus ingredientes y tu energía. Planifica tus compras y cocina con ayuda de NELDO.", "Encontre uma refeição que combine com seu tempo, seus ingredientes e sua energia. Planeje suas compras e cozinhe com ajuda do NELDO."],
['NELDO app icon','Icono de NELDO','Ícone do NELDO'],
['Plan your week','Planifica tu semana','Planeje sua semana'],
['Plan the whole week','Planifica toda la semana','Planeje a semana inteira'],
['One good meal is great.','Una buena comida está genial.','Uma boa refeição é ótima.'],
['A whole week is better.','Una semana entera, mejor.','Uma semana inteira é melhor.'],
['Plan a meal for every day, prep ahead on purpose, and shop once. Suggestions use your energy, food preferences, and allergy settings.','Planifica una comida para cada día, prepara por adelantado a propósito y haz la compra una sola vez. Las sugerencias usan tu energía, tus preferencias y tu configuración de alergias.','Planeje uma refeição para cada dia, prepare com antecedência de propósito e faça as compras uma vez só. As sugestões usam sua energia, suas preferências e suas configurações de alergia.'],
['Illustration of a sample week in NELDO: gumbo on Monday and Tuesday as meal prep, arroz con gandules, homemade ramen, shakshuka, an empty Saturday, and pollo guisado on Sunday','Ilustración de una semana de ejemplo en NELDO: gumbo el lunes y el martes como comida preparada, arroz con gandules, ramen casero, shakshuka, un sábado libre y pollo guisado el domingo','Ilustração de uma semana de exemplo no NELDO: gumbo na segunda e na terça como marmita, arroz con gandules, lámen caseiro, shakshuka, um sábado livre e pollo guisado no domingo'],
['Your week','Tu semana','Sua semana'],
['Mon – Sun','Lun – Dom','Seg – Dom'],
['Mon','Lun','Seg'],['Tue','Mar','Ter'],['Wed','Mié','Qua'],['Thu','Jue','Qui'],['Fri','Vie','Sex'],['Sat','Sáb','Sáb'],['Sun','Dom','Dom'],
['Meal prep','Comida preparada','Marmita'],
['Arroz con gandules','Arroz con gandules','Arroz com feijão-guandu'],
['Quick homemade ramen','Ramen casero rápido','Lámen caseiro rápido'],
['Shakshuka with toast','Shakshuka con pan tostado','Shakshuka com torrada'],
['Open day','Día libre','Dia livre'],
['Suggest a meal','Sugerir una comida','Sugerir uma refeição'],
['Pollo guisado','Pollo guisado','Frango ensopado'],
['Groceries for this week','Compras de esta semana','Compras desta semana'],
['14 need · 9 have','Faltan 14 · Tienes 9','Faltam 14 · Você tem 9'],
['Illustration · Sample week','Ilustración · Semana de ejemplo','Ilustração · Semana de exemplo'],
['01 / A meal for every day','01 / Una comida para cada día','01 / Uma refeição para cada dia'],
['Plan your week in one place.','Planifica tu semana en un solo lugar.','Planeje sua semana em um só lugar.'],
['Pick saved favorites, ask for suggestions, or fill only the days that are still open. Change one day without losing the rest.','Elige tus favoritas guardadas, pide sugerencias o completa solo los días que siguen libres. Cambia un día sin perder los demás.','Escolha suas favoritas salvas, peça sugestões ou preencha só os dias que ainda estão livres. Mude um dia sem perder os outros.'],
['02 / Meal prep, on purpose','02 / Preparar por adelantado, a propósito','02 / Marmita, de propósito'],
['Cook once. Eat twice.','Cocina una vez. Come dos.','Cozinhe uma vez. Coma duas.'],
['Turn on repeats and use the same recipe across days when you’re prepping ahead. NELDO won’t treat it as a mistake.','Activa las repeticiones y usa la misma receta en varios días cuando prepares por adelantado. NELDO no lo tratará como un error.','Ative as repetições e use a mesma receita em vários dias quando estiver preparando com antecedência. O NELDO não vai tratar isso como um erro.'],
['03 / Shop once','03 / Compra una vez','03 / Compre uma vez'],
['One list for the whole week.','Una lista para toda la semana.','Uma lista para a semana inteira.'],
['Ingredients from every planned day come together in one grocery list, split into what you need and what you already have.','Los ingredientes de cada día planificado se juntan en una sola lista de compras, separados entre lo que te falta y lo que ya tienes.','Os ingredientes de cada dia planejado se juntam em uma só lista de compras, separados entre o que falta e o que você já tem.'],
['04 / Goals that fit','04 / Metas a tu medida','04 / Metas do seu jeito'],
['Nutrition goals, your way.','Metas de nutrición, a tu manera.','Metas de nutrição, do seu jeito.'],
['Add goals for each meal, or for the day or week. Your allergies and foods to avoid stay part of every suggestion.','Añade metas para cada comida, o para el día o la semana. Tus alergias y los alimentos que evitas siguen presentes en cada sugerencia.','Adicione metas para cada refeição, ou para o dia ou a semana. Suas alergias e os alimentos que você evita continuam em cada sugestão.'],
['Can NELDO plan my whole week?','¿Puede NELDO planificar toda mi semana?','O NELDO pode planejar minha semana inteira?'],
['Yes. Plan one meal for each day of the week, fill open days with suggestions, and turn on repeats if you’re meal prepping. Your week’s ingredients come together in one grocery list.','Sí. Planifica una comida para cada día de la semana, completa los días libres con sugerencias y activa las repeticiones si preparas comida por adelantado. Los ingredientes de tu semana se juntan en una sola lista de compras.','Sim. Planeje uma refeição para cada dia da semana, preencha os dias livres com sugestões e ative as repetições se estiver fazendo marmitas. Os ingredientes da sua semana se juntam em uma só lista de compras.'],
['Good food, at your pace. NELDO is getting ready for iPhone and Android, starting with an adult U.S. beta. For now, explore how it works and get in touch about what’s next.','Buena comida, a tu ritmo. NELDO se está preparando para iPhone y Android, empezando con una beta para adultos en EE. UU. Por ahora, descubre cómo funciona y escríbenos sobre lo que viene.','Comida boa, no seu ritmo. O NELDO está se preparando para iPhone e Android, começando com um beta para adultos nos EUA. Por enquanto, veja como funciona e fale com a gente sobre o que vem por aí.'],
  ];
  const dictionary = new Map(rows.map(row => [row[0], row]));
  const originals = new WeakMap(), attributes = new WeakMap();
  const language = document.getElementById('language');
  let locale = 'en';
  const index = () => locale === 'es' ? 1 : locale === 'pt' ? 2 : 0;
  const translate = text => dictionary.get(text)?.[index()] ?? text;
  const render = () => {
    document.documentElement.lang = locale;
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    for (let node; (node = walker.nextNode());) {
      if (node.parentElement.closest('script,style,select,[aria-hidden="true"]')) continue;
      if (!originals.has(node)) originals.set(node, node.nodeValue);
      const original = originals.get(node), key = original.trim();
      node.nodeValue = original.replace(key, translate(key));
    }
    for (const element of document.querySelectorAll('[alt],[aria-label],meta[name="description"],meta[property^="og:"]')) {
      let saved = attributes.get(element); if (!saved) attributes.set(element, saved = {});
      for (const name of ['alt', 'aria-label', 'content']) {
        if (!element.hasAttribute(name)) continue;
        const current = element.getAttribute(name);
        if (!saved[name] || current !== saved[name].last) saved[name] = { original: current };
        const entry = saved[name]; entry.last = translate(entry.original); element.setAttribute(name, entry.last);
      }
    }
    document.title = translate(rows[0][0]);
    for (const link of document.querySelectorAll('a[href]')) {
      const url = new URL(link.href, location.href);
      if (url.origin !== location.origin) continue;
      if (!/\/(privacy|terms|how-data-works|consumer-health-data)(?:-es|-pt)?\.html$/.test(url.pathname)) continue;
      url.pathname = url.pathname.replace(/\/(privacy|terms|how-data-works|consumer-health-data)(?:-es|-pt)?\.html$/, (_, kind) => `/${kind}${locale === 'en' ? '' : '-' + locale}.html`);
      link.href = url.href;
    }
    language.value = locale;
  };
  const choose = value => { locale = ['en','es','pt'].includes(value) ? value : 'en'; render(); };
  language.addEventListener('change', () => {
    choose(language.value);
    const url = new URL(location.href);
    if (locale === 'en') url.searchParams.delete('lang'); else url.searchParams.set('lang', locale);
    history.replaceState(null, '', url);
  });
  document.addEventListener('navu-content-change', render);
  window.addEventListener('popstate', () => choose(new URLSearchParams(location.search).get('lang')));
  choose(new URLSearchParams(location.search).get('lang'));
})();
